### ISSUE TITLE
功能需求一箩筐

### ISSUE THREAD

**Issue by maocis** [ERRORawa/Scrcpy-GUI#2]
1、能不能加一个始终显示工具栏的开工
2、能否加上版本号

**Comment by ERRORawa** [comment]
第一项是说[#1](https://github.com/ERRORawa/Scrcpy-GUI/issues/1)吗，这个的话我是打算跟多任务模式一起的（没开新分支）
版本号的话…下次一定💦

**Comment by maocis** [comment]
1、工具栏自动隐藏后，不太好唤醒，我目前只能使劲摇动窗口

**Comment by ERRORawa** [comment]
嗯？我工具栏设置的是检测鼠标移动，鼠标动了即使一个像素也会显示才对

**Comment by maocis** [comment]
试出来了，在桌面上好像一动鼠标就可以出来，在别的程序的窗口上就不行了，比如我的资源管理器上，一拖动到别的程序上，工具栏就自动隐藏了，也唤醒不出来了

**Comment by ERRORawa** [comment]
知道了，应该是识别活动窗口出bug了，导致工具栏没能跟着Scrcpy一起置顶

**Comment by ERRORawa** [comment]
> 试出来了，在桌面上好像一动鼠标就可以出来，在别的程序的窗口上就不行了，比如我的资源管理器上，一拖动到别的程序上，工具栏就自动隐藏了，也唤醒不出来了

唔…可以录个视频看看吗，我这边复现不出来

**Comment by ERRORawa** [comment]
功能已经添加好了，至于自动隐藏的bug我是真复现不出来，所以你要是还需要提的话就另开个issue吧
